# Generated by Django 3.2.1 on 2021-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название курса')),
                ('start_date', models.DateField(verbose_name='Дата начала курса')),
                ('end_date', models.DateField(verbose_name='Дата окончания курса')),
                ('number_of_lectures', models.IntegerField(verbose_name='Количество лекций')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name'],
            },
        ),
    ]
